config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
  }
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  namespace :admins do
    resources :reports, only: [:index, :show, :update]
    resources :users, only: [:index, :show, :update]
    resources :reports,   only: [:index, :show, :update]
  end

  root to: "homes#top"
  get "/" => "homes#top"
  post "/" => "homes#top" # デプロイ環境でroutesエラー解消のため
  get "about" => "homes#about"
  resources :posts do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  get "search" => "posts#search"
  get "books_search" => "books#books_search"
  post "/posts/new" => "posts#new"
  resources :users, only: [:show, :edit, :update, :favorites, :withdrawal] do
    resources :reports, only: [:new, :create]
    member do
      get "withdrawal" => "users#withdrawal"
      patch "deleted" => "users#deleted"
      get "favorites" => "users#favorites"
    end
  end
  patch "users/:id" => "users#update"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy

  # 会員の利用状況
  enum status: { status_active: 0, withdrawal: 1, deactivate: 2 }

  # バリデーション
  validates :name, presence: true, length: { maximum: 10 }
  validates :profile, length: { maximum: 50 }

  # アカウントのアイコン画像
  def get_icon
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/hashibirokou.png")
      image.attach(io: File.open(file_path), filename: "default-image.png", content_type: "image/png")
    end
    image.variant(resize_to_fill: [200, 200])
  end

  # 退会済のアカウントのログイン不可
  def active_for_authentication?
    super && status_active?
  end
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin

  def index
    @users = User.all.order(created_at: :DESC)
    @users = Kaminari.paginate_array(@users).page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    # 会員ステータスの変更
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to admins_user_path(user)
    else
      flash[:notice] = "編集に失敗しました。"
      redirect_to admins_user_path(user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:id, :name, :status, :created_at)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_user, only: :create
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  # ログイン不可の時のアクション
  def reject_user
    @user = User.find_by(email: params[:user][:email])
    return if @user.nil?

    if @user.withdrawal?
      flash[:notice] = "退会済みです。再度ご登録をしてご利用ください。"
      return redirect_to new_user_registration_path
    end
    if @user.deactivate?
      flash[:notice] = "このアカウントは通報により停止されています"
      redirect_to new_user_session_path
    end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:favorites]
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc).page(params[:page]).per(5) #新着順
  end

  def edit
    @user = current_user
  end

  def update
    user = current_user
    if user.update(user_params)
      sleep(3) # S3への画像反映のタイムラグを考慮して3秒待機
      redirect_to user_path(user.id)
    else
      flash[:notice] = "編集に失敗しました。文字数は50文字までにしてください"
      redirect_to edit_user_path(current_user)
    end
  end

  def favorites
    # いいねした投稿
    favorites = Favorite.where(user_id: @user.id).order(created_at: :desc).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
    @favorite_posts = Kaminari.paginate_array(@favorite_posts).page(params[:page]).per(5)
  end

  def withdrawal
    @user = current_user
  end

  def deleted
    @user = User.find(params[:id])
    if @user.update(status: 1)
      reset_session
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to root_path
    else
      flash[:notice] = "退会処理に失敗いたしました"
      redirect_to user_path
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:profile, :image)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_post.html.erb
 <%= link_to post_path(post.id), class: "text-decoration-none text-dark" do %>
   <div class="card shadow-lg col-md-10 mx-auto mb-5">
      <div class="card-body">
        <div class="row">
          <div class="col-2">
            <%= image_tag post.user.get_icon, class: "img-thumbnail rounded-circle border" %><br>
          </div>

          <div class="col-7 ml-6">
            <i class="fas fa-user"></i> <%= post.user.name %>
          </div>
        </div>
      <!--投稿作品-->
        <div class="d-flex justify-content-around mt-2 mb-2">
          <div class="img-thumbnail"><%= image_tag(post.book.image_url) %></div>
          <div class="text-right">
           <p class="text-right"><%= post.category_i18n %></p>
           <p class="text-right"><%= post.genre_i18n %></p>
           <!--星レビュー表示-->
           <div id="star-<%= post.id %>"></div>
            <script>
              $('#star-<%= post.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= post.rate %>,
              });
            </script>  
            <!---->
          </div>
        </div>
         <h5 class="card-title border hidden">
           <%= post.book.title %>
         </h5>
       <!---->
         <h2 class="card-title border-bottom">
           <%= post.post_title %>
         </h2>
         <p class="card-text">
           <%= post.post_body %>
         </p>
         <div class="d-flex justify-content-between mt-3">
           <div class="d-flex text-right">
              <span class="mr-3">
               <span style="color:red;"><i class="fa-solid fa-heart"></i>︎</span>
               <span class="ml-1 text-dark"><%= post.favorites.count %></span>
              </span>
              <p class="mr-1">コメント件数：<%= post.comments.count %></p>
           </div>
           <div class="d-flex">
             <p class="card-text"> <%= l post.created_at %> </p>
             <!--投稿したユーザーだったら-->
             <% if @showuser == post.user %>
               <div class="text-right ml-2">
                <%= link_to"削除", post_path(post), class: "btn btn-danger", method: :delete %>
               </div>
             <% end %>
             
           </div>
         </div>
      </div>
    </div>
 <% end %>

app/views/users/_profile.html.erb
<div class="border border-2">
  <div class="text-center mt-3">
     <%= image_tag @user.get_icon, class: "img-thumbnail rounded-circle border" %>
  </div>
  <ul class="list-unstyled text-center">
    <li class="mt-3">
      <p class="h2"><%= @user.name %></p>
    </li>
    <li class="mt-3">
    <p class="h4">自己紹介<br>
      <small class="text-muted p-3"><%= @user.profile %></small>
    </p>
    </li>
    <% if @user == current_user %>
      <li>
        <%= link_to edit_user_path(current_user), class: "mt-3 btn btn-outline-dark w-75", method: :get do %>
         <i class="fa-solid fa-gear fa-lg"></i>
        <% end %>
      </li>
      <li>
        <%= link_to "いいね一覧",  favorites_user_path(current_user), class: "mt-3 btn btn-outline-dark w-75" %>
      </li>
      <li>
        <%= link_to "アカウント編集", edit_user_registration_path, class: "mt-3 btn btn-outline-dark w-75" %>
      </li>
      <li>
        <%= link_to "退会",  withdrawal_user_path(current_user), class: "mt-3 btn btn-outline-dark w-75" %>
      </li>
    <% end %>
    <div class="m-1 text-right">
      <% if @user != current_user %>
        <%= link_to new_user_report_path(@user), class: "btn btn-danger p-1", method: :get do %>
         通報<i class="fa-solid fa-ban fa-lg"></i>
        <% end %>
      <% end %>
    </div>
  </ul>


</div>

app/views/users/edit.html.erb
<div class="row">
  <!--プロフィール欄-->
  <div class="col-md-3">
   <%= render "users/profile" %>
  </div>
  <!---->
  <div class="col-md-8">
     <%= form_with model:@profile do |f| %>
      <h1>プロフィール編集</h1>
          <div class="mt-2 text-center">
            <% if @user.image.attached? %> <!--もしイメージ登録があったら-->
             <%= image_tag @user.image, size: "200x200" %>
            <% else %>
             <i class="fa-solid fa-user fa-5x border p-3 rounded-circle" style="color: gray;"></i><!--デフォルト画像-->
            <% end %>
          </div>
          <div class="text-center mt-3">
            <%= f.file_field :image, accept: "image/*" %><!--イメージ登録-->
          </div>
          <ul class="list-unstyled text-center">
            <li class="mt-3">
            <h4>自己紹介</h4>
              <%= f.text_area :profile, :size=>"40x5" %><br>
              <%= f.submit"登 録", class: "btn btn-success" %>
            </li>
          </ul>
     <% end %>
　</div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <!--プロフィール欄-->
  <div class="col-md-3">
   <%= render "users/profile" %>
  </div>
  <!---->
    <div class="col-md-8">
      <h1>いいね一覧</h1>
      <% if @favorite_posts.present? %>
      <!--投稿一覧-->
        <% @favorite_posts.each do |post| %>
           <%= render "users/post", post: post %>
        <% end %>
      <!---->
      <% else %>
        <p>いいねした投稿はありません</p>
      <% end %>
    <div class="mt-5">
        <%= paginate @favorite_posts, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <!--プロフィール欄-->
  <div class="col-md-3">
   <%= render "users/profile" %>
  </div>
  <!---->
  <div class="col-md-8">
    <h2>マイページ</h2>
    <% if @posts.present? %>
      <!--投稿一覧-->
        <% @posts.each do|post| %>
           <%= render "users/post", post: post %>
        <% end %>
      <!---->
    <% else %>
          <h4>投稿はまだありません</h4>
    <% end %>
    <div class="mt-5">
      <%= paginate @posts, theme: 'bootstrap-5' %>
     </div>
　</div>
</div>

app/views/users/withdrawal.html.erb
<div class="row">
  <!--プロフィール欄-->
  <div class="col-md-3">
   <%= render "users/profile" %>
  </div>
  <!---->
  <div class="col-md-8">

   <h1 class="m-4">退会お手続き</h1>
    <h5 class="m-5">
      退会手続きをされますと、全てのサービスがご利用いただけなくなります。<br>
      再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br>
      <br>
      本当に退会してよろしいですか？
    </h5>
    <div class= "m-5">
     <%= link_to "退会する", deleted_user_path, class: "btn btn-danger", method: :patch, data: { confilm: "本当に退会しますか？" } %>
     <%= link_to "退会しない", user_path(current_user), class: "btn btn-outline-success ml-5" %>
    </div>
　</div>
</div>