config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
  }
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  namespace :admins do
    resources :reports, only: [:index, :show, :update]
    resources :users, only: [:index, :show, :update]
    resources :reports,   only: [:index, :show, :update]
  end

  root to: "homes#top"
  get "/" => "homes#top"
  post "/" => "homes#top" # デプロイ環境でroutesエラー解消のため
  get "about" => "homes#about"
  resources :posts do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  get "search" => "posts#search"
  get "books_search" => "books#books_search"
  post "/posts/new" => "posts#new"
  resources :users, only: [:show, :edit, :update, :favorites, :withdrawal] do
    resources :reports, only: [:new, :create]
    member do
      get "withdrawal" => "users#withdrawal"
      patch "deleted" => "users#deleted"
      get "favorites" => "users#favorites"
    end
  end
  patch "users/:id" => "users#update"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # idをisbnと同一にする
  self.primary_key = "isbn"
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment_body, length: { maximum: 100 } #100
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum category: { book: 0, comic: 1 }
  enum genre: { romance: 0, fantazy: 1, action: 2, mystery: 3, sf: 4, horror: 5, comedy: 6, history: 7, human: 8, non_fiction: 9,
                gourmet: 10, sports: 11, business: 12, other: 13 }

  validates :post_title, presence: true, length: { maximum: 30 } #タイトルは30文字まで
  validates :post_body, length: { maximum: 400 } #内容は400字まで
  validates :category, presence: true
  validates :genre, presence: true
  # 星レビューの数
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
  # ランキングで使用
  scope :books, -> { Post.book }
  scope :comics, -> { Post.comic }

  # いいねしているのがログイン中のユーザーかどうか
  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 投稿作品検索
  def self.search(search_params)
    rc=joins(:book).where("books.title LIKE ?", "%#{search_params[:search]}%")
    rc=rc.where(category: search_params[:category]) if search_params[:category].present?
    rc=rc.where(genre: search_params[:genre]) if search_params[:genre].present?
    return rc
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"

  enum status: { outstanding: 0, closed: 1, unnecessary: 2 } #対応ステータス

  validates :reason, length: { maximum: 200 }
  validates :url, length: { maximum: 400 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy

  # 会員の利用状況
  enum status: { status_active: 0, withdrawal: 1, deactivate: 2 }

  # バリデーション
  validates :name, presence: true, length: { maximum: 10 }
  validates :profile, length: { maximum: 50 }

  # アカウントのアイコン画像
  def get_icon
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/hashibirokou.png")
      image.attach(io: File.open(file_path), filename: "default-image.png", content_type: "image/png")
    end
    image.variant(resize_to_fill: [200, 200])
  end

  # 退会済のアカウントのログイン不可
  def active_for_authentication?
    super && status_active?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def books_search
    @books = []
    title = params[:keyword]
    if title.present?
      # 楽天APIから検索取得したデータ（jsonデータ）
      results = RakutenWebService::Books::Book.search({
        title: title,
      })
      # APIからの取得したJSONデータを格納
      results.each do |result|
        book = Book.new(read(result))
        @books << book
      end
    end
    # 個別に保存。保存済みは除外
    @books.each do |book|
      unless Book.all.include?(book)
        book.save
      end
    end
  end

  private

  def read(result)
    title = result["title"]
    author = result["author"]
    url = result["itemUrl"]
    isbn = result["isbn"]
    image_url = result["mediumImageUrl"].gsub('?_ex=50x50', '')
    item_caption = result["itemCaption"]
    {
      title: title,
      author: author,
      url: url,
      isbn: isbn,
      image_url: image_url,
      item_caption: item_caption,
    }
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    # 新着順
    @posts = Post.all.order(created_at: :desc).page(params[:page])
    @books = Post.books.order(created_at: :desc).page(params[:book_params])
    @comics = Post.comics.order(created_at: :desc).page(params[:comic_params])

    # タイトルでの投稿数ランキング
    @ranks = Book.find(Post.group(:book_id).order('count(book_id) desc').limit(3).pluck(:book_id))
    @book_ranks = Book.find(Post.books.group(:book_id).order('count(book_id) desc').limit(3).pluck(:book_id))
    @comic_ranks = Book.find(Post.comics.group(:book_id).order('count(book_id) desc').limit(3).pluck(:book_id))

    # ジャンル検索リンク
    @genres = Post.genres_i18n
  end

  def about
  end
end

private

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @genre = params[:genre]
    @genres = Post.genres_i18n
    # search = モデルに定義している検索機能
    @search_posts = Post.search(params).page(params[:page]).order(created_at: :desc)
  end

  def new
    @post = Post.new
    @book = Book.find(params[:id])
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to post_path(@post)
    else
      @book = Book.find(params[:id])
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.order(created_at: :desc)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    if post.update(post_params)
      redirect_to post_path(params[:id])
    else
      # redirect_to post_path(params[:id])
      @post = Post.find(params[:id])
      flash.now[:alert] = "エラーが発生しました"
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    if post.destroy
      redirect_to root_path
    else
      flash[:notice] = "エラーが発生しました"
      redirect_to post_path(params[:id])
    end
  end

  def search
    # モデルに定義している検索機能
    @search_count = Post.search(params)
    @search_posts = Post.search(params).page(params[:page]).order(created_at: :desc)
  end
end

private

def post_params
  params.require(:post).permit(:book_id, :category, :genre, :post_title, :post_body, :rate)
end

def search
  params.permit(:title, :category, :genre)
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/gunres_helper.rb
module GunresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_book.html.erb
 <!--Rank-->
<div class="col-md-8 mt-3 mx-auto">
  <h3 class=" bg-white">
    <span class="crown">
      <i class="fa-solid fa-crown"></i>
    </span>
    小説Rank
  </h3>
  <div class="d-flex bg-white justify-content-around pt-3">
      <% @book_ranks.each.with_index do |rank, i| %>
        <div class="text-center d-flex" style="width: 30%;">
          <div>
            <h3><%= i + 1 %>位</h3>
            <td><%= link_to image_tag(rank.image_url), rank.url %></td>
            <span class="hidden font-weight-bold"><%= rank.title %></span>
            <%= rank.author %><br>
            <br>
            <span class="hidden2 m-3"><%= rank.item_caption %></span>
          </div>
        </div>
      <% end %>
  </div>
</div>


<div class="row">
  <div class="col-md-12 d-flex flex-wrap">
      <!--小説カテゴリーのみ表示-->
      <!--投稿一覧-->
      <% @books.each do |post| %>
       <%= render "posts/posts", post: post %>
      <% end %>
      <!---->
  </div>
  <div class="mt-5">
    <%= paginate @books, params_name: "book_params", theme: 'bootstrap-5' %>
  </div>
</div>

app/views/posts/_comic.html.erb
 <!--Rank-->
<div class="col-md-8 mt-3 mx-auto">
  <h3 class=" bg-white">
    <span class="crown">
      <i class="fa-solid fa-crown"></i>
    </span>
    マンガRank
  </h3>
  <div class="d-flex bg-white justify-content-around pt-3">
      <% @comic_ranks.each.with_index do |rank, i| %>
        <div class="text-center d-flex">
          <div>
            <h3><%= i + 1 %>位</h3>
            <td><%= link_to image_tag(rank.image_url), rank.url %></td>
            <span class="hidden font-weight-bold"><%= rank.title %></span>
            <%= rank.author %><br>
            <br>
          </div>
        </div>
      <% end %>
  </div>
</div>

<div class="row">
  <div class="col-md-12 d-flex flex-wrap">
      <% @comics.each do|post| %>
      <!--コミックカテゴリーのみ表示-->
      <!--投稿一覧-->
       <%= render "posts/posts", post: post %>
      <% end %>
      <!---->
  </div>
  <div class="mt-5">
    <%= paginate @comics, params_name: "comic_params", theme: 'bootstrap-5' %>
  </div>
</div>

app/views/posts/_genre.html.erb
<!--ジャンルリンク-->
<div class="mt-3">
  <%= form_with url: posts_path, local: true, method: :get do %>
    <% @genres.each do |genre| %>
      <div class="mr-3">
        <%= link_to genre[1], posts_path(genre: genre), class: "hover3" %><br>
      </div>
    <% end %>
  <% end %>
</div>

app/views/posts/_index.html.erb
<!--Rank-->
<div class="col-md-12">
  <div class = "row mt-3">
    <div class="col-md-5 mx-auto">
      <table class="table border bg-white">
        <h2 class=" bg-white">
          <span class="crown">
            <i class="fa-solid fa-crown"></i>
          </span>
          総合Rank
        </h2>
        <thead>
          <tr class="text-center" style="background:#FFBBFF;">
            <th>Rank</th>
            <th>作品</th>
            <th>オススメ！</th>
          </tr>
        </thead>
        <tbody>
          <% @ranks.each.with_index do |rank, i| %>
            <tr class="text-center">
              <td><strong><%= i + 1 %></strong></td>
              <td><%= link_to image_tag(rank.image_url), rank.url %></td>
              <td>
                <span class="hidden font-weight-bold"><%= rank.title %></span>
                <%= rank.author %><br>
                <br>
                <span class="hidden2"><%= rank.item_caption %></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
<!--カテゴリー別Rank-->
    <div class="col-md-5 mx-auto">
      <table class="table border bg-white">
        <h3 class=" bg-white">
          <span class="crown">
            <i class="fa-solid fa-crown"></i>
          </span>
          小説Rank
        </h3>
        <thead>
          <tr class="text-center" style="background:#FFBBFF;">
            <th>Rank</th>
            <th>作品</th>
            <th></th>
          </tr>
        </thead>
        <tbody class="al">
          <% @book_ranks.each.with_index do |rank, i| %>
            <tr class="text-center">
              <td><%= i + 1 %></td>
              <td><span class="hidden font-weight-bold"><%= rank.title %></span></td>
              <td><span class="hidden"><%= rank.author %></span></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <table class="table border bg-white">
        <h3 class=" bg-white">
          <span class="crown">
            <i class="fa-solid fa-crown"></i>
          </span>
          マンガRank
        </h3>
        <thead>
          <tr class="text-center" style="background:#FFBBFF;">
            <th>Rank</th>
            <th>作品</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @comic_ranks.each.with_index do |rank, i| %>
            <tr class="text-center">
              <td><%= i + 1 %></td>
              <td><span class="hidden font-weight-bold"><%= rank.title %></span></td>
              <td><span class="hidden"><%= rank.author %></span></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<!---->
投稿一覧
<!--投稿一覧-->
 <%= render "posts/post", posts: @posts %>
 <!---->

app/views/posts/_post.html.erb
<div class="row">
  <div class="d-flex flex-wrap">
      <% posts.each do|post| %>
        <div class="card-deck mt-3 mx-auto hover10 ">
          <%= link_to post_path(post.id), class: "text-dark text-decoration-none" do %>
            <div class="card shadow-lg post-size">
              <div class="card-body">
                <div class="row">
                  <div class="col-3"><!--アイコン-->
                    <%= image_tag post.user.get_icon, class: "img-thumbnail rounded-circle border" %><br>
                  </div>
                  <div class="col-7 ml-6">
                    <i class="fas fa-user"></i> <%= post.user.name %>
                  </div>
                </div>
                <!--投稿作品-->
                <div class="d-flex justify-content-between mt-2 mb-2">
                  <div class="img-thumbnail"><%= image_tag(post.book.image_url) %></div>
                  <div class="text-right">
                   <p class="text-right"><%= post.category_i18n %></p>
                   <p class="text-right"><%= post.genre_i18n %></p>
                  <!--星レビュー表示-->
                  <!--星の重複回避のためidをpostsテンプレート別のものを定義-->
                  <div id="star_top<%= post.id %>"></div>
                    <script>
                      $('#star_top<%= post.id %>').raty({
                        size: 36,
                        starOff:  '<%= asset_path('star-off.png') %>',
                        starOn : '<%= asset_path('star-on.png') %>',
                        starHalf: '<%= asset_path('star-half.png') %>',
                        half: true,
                        readOnly: true,
                        score: <%= post.rate %>,
                      });
                    </script>
                  <!---->
                  </div>
                </div>
                 <h5 class="card-title border hidden">
                   <%= post.book.title %>
                 </h5>
                 <!---->
                 <h4 class="card-title border-bottom hidden">
                   <%= post.post_title %>
                 </h4>
                 <p class="card-text hidden2">
                   <%= post.post_body %>
                 </p>
                 <div style="position: absolute; bottom: 0;">
                   <div class="d-flex text-right pb-3">
                       <span class="mr-3">
                             <span style="color:red;"><i class="fa-solid fa-heart"></i>︎</span>
                             <span class="ml-1 text-dark"><%= post.favorites.count %></span>
                      </span>
                      <p class="mr-1">コメント件数：<%= post.comments.count %></p>
                   </div>
                 </div>
                 <div style="position: absolute; bottom: 0; right: 0;">
                    <p class="card-text p-3">
                      <%= l post.created_at, format: :short %>
                    </p>
                 </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
  </div>
  <div class="mt-5">
    <%= paginate posts, theme: 'bootstrap-5' %>
  </div>
</div>

app/views/posts/_posts.html.erb
        <div class="card-deck mt-5 mx-auto hover10">
          <%= link_to post_path(post.id), class: "text-dark text-decoration-none" do %>
            <div class="card shadow-lg post-size">
              <div class="card-body">
                <div class="row">
                  <div class="col-3"><!--アイコン-->
                    <%= image_tag post.user.get_icon, class: "img-thumbnail rounded-circle border" %><br>
                  </div>
                  <div class="col-7 ml-6">
                    <i class="fas fa-user"></i> <%= post.user.name %>
                  </div>
                </div>
                <!--投稿作品-->
                <div class="d-flex justify-content-around mt-2 mb-2">
                  <div class="img-thumbnail"><%= image_tag(post.book.image_url) %></div>
                  <div class="text-right">
                   <p class="text-right"><%= post.category_i18n %></p>
                   <p class="text-right"><%= post.genre_i18n %></p>
                   <!--星レビュー表示-->
                   <div id="star-<%= post.id %>"></div>
                      <script>
                        $('#star-<%= post.id %>').raty({
                          size: 36,
                          starOff:  '<%= asset_path('star-off.png') %>',
                          starOn : '<%= asset_path('star-on.png') %>',
                          starHalf: '<%= asset_path('star-half.png') %>',
                          half: true,
                          readOnly: true,
                          score: <%= post.rate %>,
                        });
                      </script>
                    <!---->
                  </div>
                </div>
                 <h5 class="card-title border" style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 1;">
                   <%= post.book.title %>
                 </h5>
                 <!---->
                 <h4 class="card-title border-bottom" style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 1;">
                   <%= post.post_title %>
                 </h4>
                 <p class="card-text" style="overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 2;">
                   <%= post.post_body %>
                 </p>
                 <div style="position: absolute; bottom: 0;">
                   <div class="d-flex text-right pb-3">
                       <span class="mr-3">
                             <span style="color:red;"><i class="fa-solid fa-heart"></i>︎</span>
                             <span class="ml-1 text-dark"><%= post.favorites.count %></span>
                      </span>
                      <p class="mr-1">コメント件数：<%= post.comments.count %></p>
                   </div>
                 </div>
                 <div style="position: absolute; bottom: 0; right: 0;">
                    <p class="card-text p-3">
                      <%= l post.created_at, format: :short %>
                    </p>
                 </div>
              </div>
            </div>
          <% end %>
        </div>

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-8 mx-auto">
    <h1>投稿編集</h1>
      <%= flash[:alert] %>
      <%= form_with model: @post, url: post_path(@post.id), method: :patch do |f| %>
          <div class="form_input">
            <%= f.label :category, "カテゴリー (必須）", class: "h4 m-2" %><br>
            <%= f.collection_radio_buttons :category, Post.categories_i18n, :first, :last %>
          </div>
          <div class="form_input">
            <%= f.label :genre, "ジャンル" %><br>
             <%= f.collection_radio_buttons :genre, Post.genres_i18n, :first, :last %>
          </div>
          <div class="form-input" id="star">
            <%= f.label :rate, "作品のおすすめ度", class: "h4 m-2" %>
            <%= f.hidden_field :rate, id: :post_star, class: "form-control" %>
          </div>
          <div class="form_input">
            <%= f.label :post_title, "タイトル  (30字以内)" %>
            <%= f.text_field :post_title, class: "form-control" %>
          </div>
          <div class="form_input">
            <%= f.label :post_body, "感想 (400字以内)" %>
            <%= f.text_field :post_body, class: "form-control" %>
          </div>

          <div class="form_action row mt-3">
              <%= f.submit "編集する", class: "btn btn-primary"%>
          </div>
      <% end %>
  </div>
</div>


<script>
   $('#star').raty({
     size: 36,
     starOff:  '<%= asset_path('star-off.png') %>',
     starOn : '<%= asset_path('star-on.png') %>',
     starHalf : '<%= asset_path('star-half.png') %>',
     scoreName: 'post[rate]',
     half: true,
   });
</script>

app/views/posts/search.html.erb
<div class="row">
  <h1>投稿作品検索</h1>
  <div class="col-md-8 mx-auto">
      <%= form_with url: search_path, local: true, method: :get do |f| %>
        <div class="form-input mt-2">
          <%= f.label :title, "作品名", class: "h4" %>
          <%= f.text_field :search, class: "form-control" %>
        </div>
        <div class="form_input mt-2">
          <%= f.label :category, "カテゴリー", class: "h4" %><br>
          <%= f.collection_radio_buttons :category, Post.categories_i18n, :first, :last%>
        </div>
        <div class="form_input mt-2">
          <%= f.label :genre, "ジャンル", class: "h4" %><br>
          <%= f.collection_radio_buttons :genre, Post.genres_i18n, :first, :last %>
        </div>
        <div class="form_action row mt-4">
            <%= f.submit "検索する", class: "btn btn-primary"%>
        </div>
      <% end %>
  </div>
</div>

  <h4 class="m-4">検索結果は<%= @search_count.count %>件です</h4>
<!--検索結果投稿一覧-->
 <%= render "posts/post", posts: @search_posts %>
 <!---->

app/views/posts/show.html.erb
<div class ="row">
  <div class="card shadow-lg col-md-6 mx-auto h-100">
    <div class="card-body text-dark">
      <!--アカウント名とアイコン-->
      <div class="row">
        <div class="d-flex">
            <div class="col-2">
              <%= image_tag @post.user.get_icon, class: "img-thumbnail rounded-circle border" %><br>
            </div>

            <div class="ml-6 align-items:flex-end hover2">
              <%= link_to user_path(@post.user_id), class: "btn", method: :get do %>
                <h4><%= @post.user.name %></h4>
              <% end %>
            </div>
        </div>
      </div>
      <!---->
        <!--投稿作品-->
        <div class="d-flex justify-content-around mt-4 mb-4">
          <div class="img-thumbnail"><%=  link_to image_tag(@post.book.image_url), @post.book.url %></div>
          <div class="text-right">
           <p class="border-bottom h4"><%= @post.category_i18n %></p>
           <p class="border-bottom h5"><%= @post.genre_i18n %></p>
           <div id="star" data-score="<%= @post.rate %>">評価：</div>
          </div>
        </div>
       <h5 class="card-title border p-1">
         <%= @post.book.title %>
       </h5>
       <!---->
      <!--投稿内容-->
       <h2 class="card-title border-bottom">
         <%= @post.post_title %>
       </h2>
       <p class="card-text">
         <%= @post.post_body %>
       </p>
       <!--会員がログイン中のみ表示-->
       <% if @post.user == current_user %>
         <div class="text-right">
           <%= link_to"編集", edit_post_path(@post), class: "btn btn-primary" %>
           <%= link_to"削除", post_path(@post), class: "btn btn-danger", method: :delete, data: {confirm: "削除しますか？"} %>
         </div>
       <!--管理者がログイン中のみ表示-->
       <% elsif admin_signed_in? %>
         <div class="text-right">
           <%= link_to"削除", post_path(@post), class: "btn btn-danger", method: :delete %>
         </div>
       <% end %>
       <!---->
       <div class="d-flex">
         <span class="mr-3">
           <% if admin_signed_in? %>
              <span style="color:red;"><i class="fa-solid fa-heart"></i>︎</span>
              <span class="ml-1 text-dark"><%= @post.favorites.count %></span>
           <% elsif user_signed_in? %>
             <% if @post.favorited?(current_user) %>
                <%= link_to post_favorite_path(@post.id), method: :delete do %>
                 <span style="color:red;"><i class="fa-solid fa-heart"></i>︎</span>
                <% end %>
                 <span class="ml-1 text-dark"><%= @post.favorites.count %></span>
             <% else %>
                <%= link_to post_favorites_path(@post.id), method: :post do %>
                  <span><i class="fa-solid fa-heart"></i>︎</span>
                <% end %>
                  <span class="ml-1 text-dark"><%= @post.favorites.count %></span>
             <% end %>
           <% else %>
               <%= link_to new_user_registration_path, method: :get do %>
                 <span style="color:red;"><i class="fa-solid fa-heart"></i>︎</span>
               <% end %>
               <span class="ml-1 text-dark"><%= @post.favorites.count %></span>
           <% end %>
        </span>
        <p class="mr-5">コメント件数：<%= @post.comments.count %></p>
        <p class="card-text"><%= l @post.created_at %></p>
       </div>
    </div>
  </div>

    <!--コメント部分-->

  <div class="col-md-5">
    <div class="m-5">
      <%= form_with model: [@post, @comment] do |f| %>
        <%= f.text_area :comment_body, cols: "50", rows: "5", placeholder: "100字以内でコメントをどうぞ！" %>
        <div class="text-right"><%= f.submit "送信する", class: "btn btn-secondary" %></div>
      <% end %>
    </div>
      <% @comments.each do |comment| %>
        <div class="border border-2 mb-3 p-3">
          <div class="d-flex">
            <p class="col-2"><%= image_tag comment.user.get_icon, class: "img-thumbnail rounded-circle border" %></p>
            <%= link_to user_path(comment.user), class: "btn hover2", method: :get do %>
              <%= comment.user.name %>
            <% end %>
          </div>
          <%= comment.comment_body %><br>
          <p class="text-right m-0"><%= l comment.created_at %></p>
           <% if comment.user == current_user %>
             <div class="text-right">
               <%= link_to"削除", post_comment_path(@post, comment), class: "btn btn-danger", method: :delete, data: {confirm: "削除しますか？"}%>
             </div>
           <% elsif admin_signed_in? %>
             <div class="text-right">
               <%= link_to"削除", post_comment_path(@post, comment), class: "btn btn-danger", method: :delete, data: {confirm: "削除しますか？"} %>
             </div>
           <% end %>
        </div>
      <% end %>
  </div>

</div>

<script>
   $('#star').raty({
     size: 36,
     starOff:  '<%= asset_path('star-off.png') %>',
     starOn : '<%= asset_path('star-on.png') %>',
     starHalf : '<%= asset_path('star-half.png') %>',
     scoreName: 'post[rate]',
     half: true,
     readOnly: true,
   });
</script>