config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  devise_for :admins, controllers: {
    sessions: "admins/sessions",
    passwords: "admins/passwords",
  }
  devise_for :users, controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }

  namespace :admins do
    resources :reports, only: [:index, :show, :update]
    resources :users, only: [:index, :show, :update]
    resources :reports,   only: [:index, :show, :update]
  end

  root to: "homes#top"
  get "/" => "homes#top"
  post "/" => "homes#top" # デプロイ環境でroutesエラー解消のため
  get "about" => "homes#about"
  resources :posts do
    resources :favorites, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
  get "search" => "posts#search"
  get "books_search" => "books#books_search"
  post "/posts/new" => "posts#new"
  resources :users, only: [:show, :edit, :update, :favorites, :withdrawal] do
    resources :reports, only: [:new, :create]
    member do
      get "withdrawal" => "users#withdrawal"
      patch "deleted" => "users#deleted"
      get "favorites" => "users#favorites"
    end
  end
  patch "users/:id" => "users#update"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # idをisbnと同一にする
  self.primary_key = "isbn"
  has_many :posts, dependent: :destroy
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment_body, length: { maximum: 100 } #100
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum category: { book: 0, comic: 1 }
  enum genre: { romance: 0, fantazy: 1, action: 2, mystery: 3, sf: 4, horror: 5, comedy: 6, history: 7, human: 8, non_fiction: 9,
                gourmet: 10, sports: 11, business: 12, other: 13 }

  validates :post_title, presence: true, length: { maximum: 30 } #タイトルは30文字まで
  validates :post_body, length: { maximum: 400 } #内容は400字まで
  validates :category, presence: true
  validates :genre, presence: true
  # 星レビューの数
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
  # ランキングで使用
  scope :books, -> { Post.book }
  scope :comics, -> { Post.comic }

  # いいねしているのがログイン中のユーザーかどうか
  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 投稿作品検索
  def self.search(search_params)
    rc=joins(:book).where("books.title LIKE ?", "%#{search_params[:search]}%")
    rc=rc.where(category: search_params[:category]) if search_params[:category].present?
    rc=rc.where(genre: search_params[:genre]) if search_params[:genre].present?
    return rc
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :reporter, class_name: "User"
  belongs_to :reported, class_name: "User"

  enum status: { outstanding: 0, closed: 1, unnecessary: 2 } #対応ステータス

  validates :reason, length: { maximum: 200 }
  validates :url, length: { maximum: 400 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :reports, class_name: "Report", foreign_key: "reporter_id", dependent: :destroy
  has_many :reverse_of_reports, class_name: "Report", foreign_key: "reported_id", dependent: :destroy

  # 会員の利用状況
  enum status: { status_active: 0, withdrawal: 1, deactivate: 2 }

  # バリデーション
  validates :name, presence: true, length: { maximum: 10 }
  validates :profile, length: { maximum: 50 }

  # アカウントのアイコン画像
  def get_icon
    unless image.attached?
      file_path = Rails.root.join("app/assets/images/hashibirokou.png")
      image.attach(io: File.open(file_path), filename: "default-image.png", content_type: "image/png")
    end
    image.variant(resize_to_fill: [200, 200])
  end

  # 退会済のアカウントのログイン不可
  def active_for_authentication?
    super && status_active?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/gunres_helper.rb
module GunresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doremiru</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
     <!--<BootstrapのCSS動作用>-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <!--<BootstrapのJavascript動作用>-->
     <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
    <!---->
    <!--fontawesomeのCDNコード-->
    <script src="https://kit.fontawesome.com/2c3be2f810.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <header class="bg-info">
      <div class="d-flex flex-column">
        <nav class="navbar navbar-expand-lg navbar-light p-1">
          <a class="navbar-brand bg-white rounded p-0 d-flex align-items-center" href="/">
            <h1 class="font-weight-bold">どれみる</h1><%= image_tag"megane.png", size: "180x50" %>
          </a>
          <button class="navbar-toggler bg-white" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
            aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li>
                 <%= link_to"TOP", root_path, class: "nav-item hover"%>
                </li>
                <li>
                 <%= link_to"投稿検索", search_path, class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"会員一覧", admins_users_path, class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"通報一覧", admins_reports_path, class: "nav-item hover" %>
                </li>
                 <li>
                 <%= link_to"ログアウト", destroy_admin_session_path, class: "nav-item hover" %>
                </li>
              <% elsif user_signed_in? %>
                <li>
                 <%= link_to"TOP", root_path, class: "nav-item hover"%>
                </li>
                <li></li>
                 <%= link_to"About", about_path, class: "nav-item hover"%>
                </li>
                <li>
                 <%= link_to"投稿検索", search_path, class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"新規投稿", books_search_path, class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"マイページ", user_path(current_user), class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"ログアウト", destroy_user_session_path, class: "nav-item hover" %>
                </li>
              <% else %>
                <li>
                 <%= link_to"TOP", root_path, class: "nav-item hover"%>
                </li>
                <li>
                 <%= link_to"About", about_path, class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"投稿検索", search_path, class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"新規登録", new_user_registration_path, class: "nav-item hover" %>
                </li>
                <li>
                 <%= link_to"ログイン", new_user_session_path, class: "nav-item hover" %>
                </li>
              <% end %>
            </ul>
           </div>
        </nav>
      </div>
    </header>
     <div class="col-md-12">
        <div class="m-4">
          <div class="notifications">
            <div class="h4 text-danger">
              <%= flash[:notice] %>
              </div>
          </div>
           <%= yield %>
        </div>
     </div>
    <footer class="footer bg-info">
      <div class=" d-flex align-items-center justify-content-center" style="height: 40px;">
        <div class="bg-white rounded">どれみる?</div>
    　　<%= image_tag"developers_logo.svg", size: "150x40" %>
        <%= link_to"管理者はこちら", new_admin_session_path, class: "pl-1" %>
      </div>
    </footer>
  </body>
</html>